@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
class Account {
--Attribute--
- Player
--Operations--
+ Account (Player)
}

class Player {
--Attribute--
-Name
--Operation--
+getName()
}
class DieCup {
--Attribute--
- FaceValue1
- FaceValue2
- maxFaceValue
- sum
--Operation--
+roll()
+DieCup(int DieSides)
}
class Print {
--Attribute--
--Operation--
+player1Name()
+player2Name()
+randomStart()
+whoStarts(name)
}

class Game {
--Attribute--
-Player1
-Player2
-coin
--Operation--
+gameStart()
}
Player - Print
Print - Game
Game - DieCup
DieCup - Account
@enduml