@startuml
'https://plantuml.com/sequence-diagram

Actor Player as Player

Player -> System: GameStart()
loop while points<3000
System -> RandomCalculator: DieCup.roll()
RandomCalculator --> System: getSum()
System -> Board: getSquare(dieSum)
Board --> System: getSquare()
System --> Player: print(DieCup.sum)
System --> Player: print(getSquare)
System -> Board: getValue(dieSum)
Board --> System: getValue()
System -> Account: addPoints()
Account --> System: getBalance()
System --> Player: print(getBalance)
end

@enduml